site_name: My Docs

nav:
  - index.md
  - Blog:
    - blog/index.md

theme:
   name: material

   features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections

   palette: 

    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep purple
      accent: indigo
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep purple
      accent: indigo

   
plugins:
  - blog