site_name: Ethan Childs

nav:
  - index.md
  - Projects: projects.md
  - Blog:
    - blog/index.md

theme:
   name: material

   custom_dir: docs/overrides

   features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - search.suggest
    - search.highlight

   palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

   
plugins:
  - blog
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ethanchilds
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ethanchilds13/