site_name: Ethan Childs

nav:
  - index.md
  - Blog:
    - blog/index.md

theme:
   name: material

   features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - search.suggest
    - search.highlight

   palette: 

    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep purple
      accent: indigo
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep purple
      accent: indigo

   
plugins:
  - blog
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ethanchilds
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ethanchilds13/